test.tex: pyptex compilation begins
Found 1 lines of Python.
argv differs ['foo'] []
Cache is invalidated.
Executing Python code:
print("runtestsargv-2 foo")
runtestsargv-2 foo
Python result:
[None]
Saving to file: test.pyptex
Dependencies are:
{'.../__init__.py': '(datetime)'}
Saving cache file test.pickle
Running Latex command:
pdflatex -file-line-error --synctex=1 test.pyptex && (test ! -f test.bib || bibtex test.aux)
